blog/config/routes.rb
Rails.application.routes.draw do

  root to: 'blog_apps#welcome'
  resources :blog_apps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/blog_app.rb
class BlogApp < ApplicationRecord
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

blog/app/controllers/blog_apps_controller.rb
class BlogAppsController < ApplicationController
  before_action :set_blog_app, only: [:show, :edit, :update, :destroy]

  # GET /blog_apps
  # GET /blog_apps.json
  def index
    @blog_apps = BlogApp.all
  end


  # GET /blog_apps/new
  def new
    @blog_app = BlogApp.new
  end

  # POST /blog_apps
  # POST /blog_apps.json
  def create
    @blog_app = BlogApp.new(blog_app_params)

    respond_to do |format|
      if @blog_app.save
        format.html { redirect_to @blog_app, notice: 'Blog app was successfully created.' }
        format.json { render :show, status: :created, location: @blog_app }
      else
        format.html { render :new }
        format.json { render json: @blog_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_apps/1
  # PATCH/PUT /blog_apps/1.json
  def update
    respond_to do |format|
      if @blog_app.update(blog_app_params)
        format.html { redirect_to @blog_app, notice: 'Blog app was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_app }
      else
        format.html { render :edit }
        format.json { render json: @blog_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_apps/1
  # DELETE /blog_apps/1.json
  def destroy
    @blog_app.destroy
    respond_to do |format|
      format.html { redirect_to blog_apps_url, notice: 'Blog app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_app
      @blog_app = BlogApp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_app_params
      params.require(:blog_app).permit(:topic, :body)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/blog_apps_helper.rb
module BlogAppsHelper
end

blog/app/views/blog_apps/_form.html.erb
<%= form_with(model: blog_app, local: true) do |form| %>
  <% if blog_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_app.errors.count, "error") %> prohibited this blog_app from being saved:</h2>

      <ul>
      <% blog_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/blog_apps/edit.html.erb
<h1>Editing Blog App</h1>

<%= render 'form', blog_app: @blog_app %>

<%= link_to 'Show', @blog_app %> |
<%= link_to 'Back', blog_apps_path %>

blog/app/views/blog_apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Apps</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_apps.each do |blog_app| %>
      <tr>
        <td><%= blog_app.topic %></td>
        <td><%= blog_app.body %></td>
        <td><%= link_to 'Show', blog_app %></td>
        <td><%= link_to 'Edit', edit_blog_app_path(blog_app) %></td>
        <td><%= link_to 'Destroy', blog_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog App', new_blog_app_path %>

blog/app/views/blog_apps/new.html.erb
<h1>New Blog App</h1>

<%= render 'form', blog_app: @blog_app %>

<%= link_to 'Back', blog_apps_path %>

blog/app/views/blog_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @blog_app.topic %>
</p>

<p>
  <div class="wrapper">
  <strong>Body:</strong>
  <%= @blog_app.body %>
  </div>
</p>

<%= link_to 'Edit', edit_blog_app_path(@blog_app) %> |
<%= link_to 'Back', blog_apps_path %>

blog/app/views/blog_apps/welcome.html.erb
<h1> Welcome to our blog </h1>

<%= link_to 'Top Stories', blog_apps_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header><nav><%= link_to 'Home', root_path %></nav></header>
    <main class="main">
      <%= yield %>
    </main>
  </body>
</html>